POST http://localhost:3000/api/users/register-user
Content-Type: application/json

{
    "firstName": "bev",
    "lastName": "Limo",
    "email": "bevlimo@gmail.com",
    "password":"genbev@1234"
}

###
POST http://localhost:3000/api/users/login-user
Content-Type: application/json

{
    "email": "bevlimo@gmail.com",
    "password":"genbev@1234"
}

###
GET http://localhost:3000/api/users/name
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmVlZDhmODEwNWU1ZDgwMWI2MjIzNDEiLCJpYXQiOjE3MjY5OTk1NTAsImV4cCI6MTcyNzAwMTM1MH0.e5J745mdLsOtaVQIA4qhdRxrvyw7maxMHo5JLTXKfzg


###
POST http://localhost:3000/api/errands/create-errand
Content-Type: application/json

{
  "errandName": "Grocery Pickup",
  "errandImage": "https://example.com/images/grocery-pickup.png",
  "description": "Pick up groceries from the supermarket and deliver to my home.",
  "county": "Nairobi",
  "subCounty": "Westlands",
  "place": "Westgate Shopping Mall",
  "dateTime": "2024-09-25T14:30:00",
  "completionTime": "2024-09-25T16:00:00",
  "urgency": "High",
  "instructions": "Get fresh vegetables and fruits, and make sure to pick the items from the provided list.",
  "status": "Pending"
}

###
GET http://localhost:3000/api/errands/all

###
GET http://localhost:3000/api/errands/errand/66f3122827ac9a82b8b4cab5

###
PUT http://localhost:3000/api/errands/update/errand/66f3192dd8ec02c9cf7131f3
Content-Type: application/json

{
  "errandName": "Grocery Pickup",
  "errandImage": "https://example.com/images/grocery-pickup.png",
  "description": "Pick up groceries from the supermarket and deliver to my home.",
  "county": "Nairobi",
  "subCounty": "Kilimani",
  "place": "Westgate Shopping Mall",
  "dateTime": "2024-09-25T14:30:00",
  "completionTime": "2024-09-25T16:00:00",
  "urgency": "Medium",
  "instructions": "Get fresh vegetables and fruits, and make sure to pick the items from the provided list.",
  "status": "Pending"
}

###
DELETE http://localhost:3000/api/errands/delete/errand/66f3122827ac9a82b8b4cab5
